version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  create_and_deploy_front_end:
    docker:
    - image: amazon/aws-cli
      auth:
         username: $AccessKeyID
         password: $SecretaccessKey
    steps:
      - checkout
      - run: | #Create Bucket
          aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name stack-${CIRCLE_WORKFLOW_ID} \
            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" --region=us-west-2
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete #Sync local & bucket

  promote_to_production:
    docker:
    - image: amazon/aws-cli
      auth:
         username: $AWS_ACCOUNT_ID
         password: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run: | #interacts with CloudFront to change from Old Bucket to new
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}" --region=us-west-2


workflows:
  default:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
            requires: 
              - create_and_deploy_front_end



