version: 2.1

jobs:
  create_and_deploy_front_end:
    docker:
    - image: amazon/aws-cli
      auth:
         username: Aurond
         password: $SecretaccessKey
    steps:
      - checkout
      - run: | #Create Bucket
          aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "${CIRCLE_WORKFLOW_ID}" \
            --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID}" --region=us-west-2
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete #Sync local & bucket

  promote_to_production:
    docker:
    - image: amazon/aws-cli
      auth:
         username: $AccessKeyID
         password: $SecretaccessKey
    steps:
      - checkout
      - run: | #interacts with CloudFront to change from Old Bucket to new
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}" --region=us-west-2


workflows:
  default:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
            requires: 
              - create_and_deploy_front_end



